### ISSUE TITLE
Add external dependecies section in platformio.ini with exact versions

### ISSUE THREAD

**Issue by saikek** [CosmicMac/ESParkle#1]
Hi!

Can you please add external dependecies section inside platformio.ini with exact versions that worked for you? (or at least list them)
This way platformio would pull libraries automatically.
There are often breaking changes, so project does not compile for me, because of ArudinoJson newer version.
```
lib_deps_external =
    ArduinoJson@~5.6,!=5.4
    https://github.com/gioblu/PJON.git#v2.0
    IRremoteESP8266=https://github.com/markszabo/IRremoteESP8266/archive/master.zip
```

See docu on that:
https://docs.platformio.org/en/latest/projectconf.html

**Comment by momo90-2** [comment]
I would also appreciate that. With the latest libraries your code doesnt compile

**Comment by CosmicMac** [comment]
Well, I finally did it... I changed my PC since this project and some libraries were globally installed on the old one (not accessible at the moment), so I had to dig a bit to find the exact working version. You should be able to compile successfully now. BTW, it would probably be a good idea to refresh it with newer versions of the libs. Unfortunately, I have no time left for playing with MCUs at the moment.
